'use client'

import { useEffect } from 'react'
import toast from 'react-hot-toast'

const UPDATE_CHECK_EVERY_MS = 30 * 60 * 1000

/**
 * "Update available" prompt for new deploys.
 *
 * next-pwa registers the service worker with skipWaiting + clientsClaim, so a
 * new deploy's SW activates and takes control immediately — but the open page
 * still runs the OLD code until it reloads. Reloading automatically (as this
 * used to) could wipe a half-written post or form, so we ask instead.
 *
 * An installed app can stay open for days and SPA navigations never re-check
 * the SW, so we also ask the browser to look for a new deploy whenever the app
 * comes back to the foreground (at most every 30 minutes).
 *
 * We only listen when a controller already exists, so the very first install
 * (controller: null → SW) does NOT prompt.
 */
export default function SWUpdater() {
  useEffect(() => {
    if (typeof window === 'undefined' || !('serviceWorker' in navigator)) return

    // Older builds cached per-member API responses on the device; drop them.
    if ('caches' in window) caches.delete('sisterroam-api-cache').catch(() => {})

    // next-pwa's `register: true` injects its registration into the Pages-Router
    // entry chunk, which App-Router pages never load — so the service worker
    // (offline page, update handling) was never installed. Register it here.
    // Production only: /sw.js is generated by `next build`.
    if (process.env.NODE_ENV === 'production') {
      navigator.serviceWorker.register('/sw.js', { scope: '/' }).catch(() => {})
    }

    let lastCheck = Date.now()
    const onVisible = () => {
      if (document.visibilityState !== 'visible') return
      if (Date.now() - lastCheck < UPDATE_CHECK_EVERY_MS) return
      lastCheck = Date.now()
      navigator.serviceWorker.getRegistration().then((reg) => reg?.update()).catch(() => {})
    }
    document.addEventListener('visibilitychange', onVisible)

    // No existing controller means this is the first install — its initial claim
    // is not an update.
    const hadController = !!navigator.serviceWorker.controller
    let prompted = false
    const onControllerChange = () => {
      if (!hadController || prompted) return
      prompted = true
      toast(
        (t) => (
          <span className="flex items-center gap-3 text-sm">
            A new version of SisterRoam is available.
            <button
              type="button"
              onClick={() => { toast.dismiss(t.id); window.location.reload() }}
              className="shrink-0 px-3 py-1.5 rounded-lg bg-brand text-white font-medium"
            >
              Refresh
            </button>
          </span>
        ),
        { id: 'sw-update', duration: Infinity },
      )
    }
    navigator.serviceWorker.addEventListener('controllerchange', onControllerChange)

    return () => {
      document.removeEventListener('visibilitychange', onVisible)
      navigator.serviceWorker.removeEventListener('controllerchange', onControllerChange)
    }
  }, [])

  return null
}
